version: "3"

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mos123
      MYSQL_DATABASE: mos
      MYSQL_USER: mos
      MYSQL_PASSWORD: mos123

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8181:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: mos
      PMA_PASSWORD: mos123

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
